import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
<html>
  <body className="min-h-screen w-full overflow-x-hidden bg-white">
    <Navbar />

    <main className="mx-auto w-full max-w-6xl px-4">
      {children}
    </main>
    <Footer/>
  </body>
</html>
  );
}
